version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/application"
    schedule:
      interval: "daily"
